# Generated by Django 5.0.6 on 2024-05-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0002_book_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_first_name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_last_name',
        ),
    ]
