# Generated by Django 5.0.6 on 2024-05-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0003_rename_author_first_name_book_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='book',
            new_name='books',
        ),
        migrations.CreateModel(
            name='TotalBookCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_books.book')),
            ],
        ),
    ]
