# Generated by Django 5.0.6 on 2024-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0004_rename_book_bookshelf_books_totalbookcatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('NONFICTION', 'Non-Fiction'), ('MYSTERY', 'Mystery'), ('THRILLER', 'Thriller'), ('HORROR', 'Horror'), ('SCI-FI', 'Science Fiction'), ('FANTASY', 'Fantasy'), ('ROMANCE', 'Romance'), ('BIOGRAPHY', 'Biography'), ('POETRY', 'Poetry'), ('HISTORICAL', 'Historical'), ('SELF_HELP', 'Self Help'), ('CHILDREN', 'Children’s'), ('YOUNG_ADULT', 'Young Adult'), ('EDUCATION', 'Education'), ('COMIC', 'Comic Book'), ('GRAPHIC_NOVEL', 'Graphic Novel'), ('BUSINESS', 'Business'), ('TECHNOLOGY', 'Technology'), ('COOKING', 'Cooking'), ('TRAVEL', 'Travel'), ('RELIGION', 'Religion'), ('TRUE_CRIME', 'True Crime'), ('SPORTS', 'Sports'), ('MUSIC', 'Music'), ('ART', 'Art')], max_length=50),
        ),
        migrations.DeleteModel(
            name='TotalBookCatalog',
        ),
    ]
