# Generated by Django 5.0.6 on 2024-05-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0007_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='title',
            field=models.CharField(default='Book Shelf', max_length=100, unique=True),
        ),
    ]
